[package]
name = "api-fuzzkit"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version ="4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }